name: Checks and Linters

on:
  push:

jobs:
  # security:
  #   uses: lidofinance/linters/.github/workflows/security.yml@master # It looks like codeql can't recognize language needs to improve here

  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master

  actions:
    uses: lidofinance/linters/.github/workflows/actions.yml@master
