name: Checks and Linters

on:
  push:

jobs:
  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
    with:
      skip-codeql: true

  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master

  actions:
    uses: lidofinance/linters/.github/workflows/actions.yml@master

  domain-agnostic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Run checks
        run: |
          set -e

          echo Check format...
          yarn format

          echo Checking explicit domain usage
          ./scripts/check-domain-agnostic.mjs

          set +e
