name: CI Build prod image

on:
  release:
    types: [released]

permissions: {}

jobs:
  # test:
  #   ...

  deploy:
    runs-on: ubuntu-latest
    # needs: test
    name: Build and deploy
    steps:
      - name: Build prod image
        uses: lidofinance/dispatch-workflow@f6160026f09afc4076f8350b5e23a1a12e2c36b6 # v1
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: "lidofinance/infra-mainnet"
          TAG: "${{ github.event.release.tag_name }}"
          TARGET_WORKFLOW: "build_critical_lido_content.yaml"
