name: Weekly fetch of audits count

on:
  push:
  schedule:
    # At 12:00 on Monday
    - cron: '0 12 * * MON' 

jobs:
  fetch-audits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Create fetcher script
        run: |
          cat <<EOF > /tmp/fetch-audits.js
          const API_URL = 'https://api.github.com/repos/lidofinance/audits/contents/';

          async function countPdfFiles(path = '') {
            const response = await fetch(API_URL + path);
            const data = await response.json();
            let count = 0;

            for (const item of data) {
              if (item.type === 'file' && item.name.endsWith('.pdf')) {
                count++;
              } else if (item.type === 'dir') {
                count += await countPdfFiles(item.path);
              }
            }

            return count;
          }

          countPdfFiles().then(count => {
            console.log('count', count);
          });

          EOF
          
      - name: Execute fetcher script
        run: node /tmp/fetch-audits.js
