name: Prepare release draft
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  prepare-release-draft:
    permissions:
      contents: write # the called workflow creates a release draft
    uses: lidofinance/actions/.github/workflows/prepare-release-draft.yml@c7b5b6c5d8013046347d728d748fa741eb214e28 # main
    with:
      target: main
